#!/usr/bin/env node
// night-run/sql-conversion/convert.mjs
//
// Converts the 3 SQL-adapted problems (weather-observation-station-5,
// occupations, 15-days-of-learning-sql) from stdin/stdout adaptations into
// REAL SQL problems (language "sql" = Judge0 82, SQLite 3.27.2):
//
//   - languages: ["sql"], stubs: sql only (schema-comment header)
//   - statement: original SQL task wording + a prominent SQLite-dialect note
//     + the schema as markdown tables (the stdin-framing preamble is dropped)
//   - tests: input = the hidden seed SQL (CREATE+INSERT) transformed from the
//     existing stdin datasets in ../hr-clone-386632/extraction-sql-adapted.json;
//     expected = MACHINE-GENERATED by running the reference query through a
//     LOCAL sqlite3 with the IDENTICAL composition the exec handlers use
//     (composeSqlExecSource — imported, not copied). Never hand-typed.
//
// Validation (always, before any write): every regenerated expected output
// must equal the adapted problem's original expected output byte-for-byte
// (the Python solvers and the SQL reference must agree on the same data), and
// every seed/expected must fit PROBLEM_BOUNDS.TEST_TEXT_MAX. If a seed ever
// exceeds the bound, trim dataset rows (keeping the answer stable) and let
// this script re-derive the expected — do NOT hand-edit outputs.
//
// Usage:
//   node convert.mjs                  # validate only; writes payloads.json
//   ADMIN_PASSWORD=... node convert.mjs        # validate, then POST to the API
//   ADMIN_PASSWORD=... node convert.mjs --dry-run   # force validate-only
//
// API base defaults to the dev deployment; override with PROCTOR_API.
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { composeSqlExecSource, PROBLEM_BOUNDS } from "../../backend/src/problems.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const EXTRACTION = join(HERE, "..", "hr-clone-386632", "extraction-sql-adapted.json");
const PAYLOADS_OUT = join(HERE, "payloads.json");
const API = process.env.PROCTOR_API || "https://proctor-api-ej4cpz43iq-el.a.run.app";
const DRY_RUN = process.argv.includes("--dry-run");

// ---- local sqlite3 pipeline ---------------------------------------------------

function checkSqlite3() {
  const probe = spawnSync("sqlite3", ["--version"], { encoding: "utf8" });
  if (probe.status !== 0) {
    console.error("FATAL: local sqlite3 not available (needed to machine-generate expected outputs)");
    process.exit(1);
  }
  return probe.stdout.trim().split(" ")[0];
}

// Mirror of the engine's run shape: the composed script is fed to sqlite3 on a
// fresh database (Judge0 redirects the script file into `sqlite3 /box/db.sqlite`;
// a no-arg local sqlite3 opens a transient in-memory db — same blank slate).
function runSqlite(script) {
  const run = spawnSync("sqlite3", [], { input: script, encoding: "utf8" });
  if (run.status !== 0) {
    throw new Error(`sqlite3 exited ${run.status}: ${run.stderr}`);
  }
  if (run.stderr && run.stderr.trim()) {
    throw new Error(`sqlite3 wrote to stderr: ${run.stderr}`);
  }
  return run.stdout.replace(/\n+$/, "");
}

const sq = (value) => `'${String(value).replace(/'/g, "''")}'`;

// ---- seed builders (stdin dataset -> CREATE+INSERT) ----------------------------
// Deterministic filler values for columns the answer never touches (ID, STATE,
// LAT_N/LONG_W, submission_id, score) keep the advertised schema real without
// affecting any expected output.

const STATES = ["TN", "KA", "MH", "DL", "KL", "AP", "GA", "WB"];

function ws5Seed(stdin) {
  const lines = stdin.replace(/\n+$/, "").split("\n");
  const n = Number(lines[0]);
  const cities = lines.slice(1, 1 + n);
  const rows = cities.map((city, i) =>
    `(${i + 1}, ${sq(city)}, ${sq(STATES[i % STATES.length])}, ${(8 + i)}.${(i * 3) % 10}, ${(70 + i)}.${(i * 7) % 10})`);
  return [
    "CREATE TABLE STATION (ID INTEGER, CITY VARCHAR(50), STATE VARCHAR(2), LAT_N NUMERIC, LONG_W NUMERIC);",
    "INSERT INTO STATION (ID, CITY, STATE, LAT_N, LONG_W) VALUES",
    rows.join(",\n") + ";"
  ].join("\n");
}

function occSeed(stdin) {
  const lines = stdin.replace(/\n+$/, "").split("\n");
  const n = Number(lines[0]);
  const rows = lines.slice(1, 1 + n).map((line) => {
    const [name, occupation] = line.split(" ");
    return `(${sq(name)}, ${sq(occupation)})`;
  });
  return [
    "CREATE TABLE OCCUPATIONS (Name VARCHAR(50), Occupation VARCHAR(20));",
    "INSERT INTO OCCUPATIONS (Name, Occupation) VALUES",
    rows.join(",\n") + ";"
  ].join("\n");
}

function d15Seed(stdin) {
  const lines = stdin.replace(/\n+$/, "").split("\n");
  const [h, s] = lines[0].split(" ").map(Number);
  const hackers = lines.slice(1, 1 + h).map((line) => {
    const [id, name] = line.split(" ");
    return `(${Number(id)}, ${sq(name)})`;
  });
  const subs = lines.slice(1 + h, 1 + h + s).map((line, i) => {
    const [day, hackerId] = line.split(" ").map(Number);
    const date = `2016-03-${String(day).padStart(2, "0")}`;
    const score = ((i + 1) * 7) % 91 + 10; // deterministic filler
    return `(${sq(date)}, ${i + 1}, ${hackerId}, ${score})`;
  });
  return [
    "CREATE TABLE Hackers (hacker_id INTEGER, name VARCHAR(50));",
    "CREATE TABLE Submissions (submission_date DATE, submission_id INTEGER, hacker_id INTEGER, score INTEGER);",
    "INSERT INTO Hackers (hacker_id, name) VALUES",
    hackers.join(",\n") + ";",
    "INSERT INTO Submissions (submission_date, submission_id, hacker_id, score) VALUES",
    subs.join(",\n") + ";"
  ].join("\n");
}

// ---- reference queries (SQLite 3.27-safe: window functions OK; no FILTER, no
// RIGHT JOIN, no CONCAT() — `||` only) -------------------------------------------

const WS5_REF = `SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) ASC, CITY ASC LIMIT 1;
SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC, CITY ASC LIMIT 1;`;

const OCC_REF = `SELECT
  MAX(CASE WHEN Occupation = 'Doctor' THEN Name END),
  MAX(CASE WHEN Occupation = 'Professor' THEN Name END),
  MAX(CASE WHEN Occupation = 'Singer' THEN Name END),
  MAX(CASE WHEN Occupation = 'Actor' THEN Name END)
FROM (
  SELECT Name, Occupation,
         ROW_NUMBER() OVER (PARTITION BY Occupation ORDER BY Name) AS rn
  FROM OCCUPATIONS
)
GROUP BY rn
ORDER BY rn;`;

const D15_REF = `WITH days AS (
  SELECT DISTINCT submission_date AS d FROM Submissions
),
streak_members AS (
  SELECT days.d AS d, s.hacker_id AS hacker_id
  FROM days
  JOIN Submissions s ON s.submission_date <= days.d
  GROUP BY days.d, s.hacker_id
  HAVING COUNT(DISTINCT s.submission_date) =
         (SELECT COUNT(DISTINCT s2.submission_date) FROM Submissions s2 WHERE s2.submission_date <= days.d)
),
streaks AS (
  SELECT d, COUNT(*) AS cnt FROM streak_members GROUP BY d
),
ranked AS (
  SELECT submission_date AS d, hacker_id,
         ROW_NUMBER() OVER (PARTITION BY submission_date ORDER BY COUNT(*) DESC, hacker_id ASC) AS rn
  FROM Submissions
  GROUP BY submission_date, hacker_id
)
SELECT days.d, COALESCE(streaks.cnt, 0), ranked.hacker_id, h.name
FROM days
JOIN ranked ON ranked.d = days.d AND ranked.rn = 1
JOIN Hackers h ON h.hacker_id = ranked.hacker_id
LEFT JOIN streaks ON streaks.d = days.d
ORDER BY days.d;`;

// ---- statements -----------------------------------------------------------------

const DIALECT_NOTE = `**SQLite dialect (3.27).** Your query runs against a pre-loaded SQLite 3.27 database. Write standard SQLite SQL — use \`||\` for string concatenation; \`RIGHT JOIN\`, \`FILTER\` and \`CONCAT()\` are **not** available. Output formatting is preconfigured: result columns print space-separated and SQL \`NULL\` prints as \`NULL\`. Submit only SQL statements — no input reading, no print code. Multiple statements are allowed; their results print in order.`;

const WS5_STATEMENT = `Query the two cities in **STATION** with the **shortest** and **longest** *CITY* names, as well as their respective lengths (i.e. number of characters in the name, spaces included).

If there is more than one smallest or largest city, choose the one that comes first when ordered alphabetically.

${DIALECT_NOTE}

### Schema

The **STATION** table is already loaded:

| Field | Type |
| --- | --- |
| ID | INTEGER |
| CITY | VARCHAR(50) |
| STATE | VARCHAR(2) |
| LAT_N | NUMERIC |
| LONG_W | NUMERIC |

where *LAT_N* is the northern latitude and *LONG_W* is the western longitude. City names may contain spaces.

### Output Format

Two lines:

- Line 1: the city with the shortest name, then the length of its name.
- Line 2: the city with the longest name, then the length of its name.

(If STATION has a single city, the same city appears on both lines. Two \`SELECT\` statements — shortest first — are the natural shape.)

### Sample

For the sample database (the seed data is visible in the sample test), the output is:

\`\`\`
Amo 3
Marine On Saint Croix 21
\`\`\`

The shortest name is "Amo" (3 characters; "Goa" also has 3 but "Amo" comes first alphabetically). The longest is "Marine On Saint Croix" (21 characters, spaces included).`;

const OCC_STATEMENT = `[Pivot](https://en.wikipedia.org/wiki/Pivot_table) the *Occupation* column of the **OCCUPATIONS** table so that each *Name* is sorted alphabetically and displayed underneath its corresponding *Occupation*. The output should consist of four columns — **Doctor**, **Professor**, **Singer**, and **Actor** — in that specific order, with names listed alphabetically (top to bottom) under each column.

**Note:** Print **NULL** when there are no more names corresponding to an occupation.

${DIALECT_NOTE}

### Schema

The **OCCUPATIONS** table is already loaded:

| Column | Type |
| --- | --- |
| Name | VARCHAR(50) |
| Occupation | VARCHAR(20) |

*Occupation* is always one of: Doctor, Professor, Singer or Actor. Names are unique.

### Output Format

Print the pivot table row by row: each result row has exactly four values (Doctor column, Professor column, Singer column, Actor column), with \`NULL\` filling columns that have run out of names. The number of rows equals the size of the largest occupation group.

### Sample

For the sample database (the seed data is visible in the sample test), the output is:

\`\`\`
Samantha Ashley Jenny Jane
NULL Christeen Meera Julia
NULL Ketty Priya Maria
\`\`\`

The only Doctor is Samantha. The Professors, alphabetically, are Ashley, Christeen, Ketty. The Singers are Jenny, Meera, Priya. The Actors are Jane, Julia, Maria. Columns shorter than the longest (3 rows) are padded with NULL.`;

const D15_STATEMENT = `Julia conducted a **15 Days of Learning SQL** contest. The start date of the contest was *March 01, 2016* and the end date was *March 15, 2016*.

Write a query to print the total number of unique hackers who made at least 1 submission **each day** (starting on the first day of the contest), and find the *hacker_id* and *name* of the hacker who made the **maximum** number of submissions **each day**. If more than one such hacker has the maximum number of submissions, print the one with the **lowest** *hacker_id*. The query should print this information for each day of the contest, sorted by the date.

${DIALECT_NOTE}

### Schema

The **Hackers** table is already loaded:

| Column | Type |
| --- | --- |
| hacker_id | INTEGER |
| name | VARCHAR(50) |

The **Submissions** table is already loaded:

| Column | Type |
| --- | --- |
| submission_date | DATE (\`'YYYY-MM-DD'\` text, \`'2016-03-01'\` … \`'2016-03-15'\`) |
| submission_id | INTEGER |
| hacker_id | INTEGER |
| score | INTEGER |

Only days that have at least one submission appear in the data; days are not guaranteed to be contiguous in the table order.

### Output Format

For each contest day that has at least one submission, in date order, print one row with four values: the date (\`2016-03-DD\`), the number of unique hackers who made at least 1 submission on **every** contest day so far (up to and including that day), and the *hacker_id* and *name* of that day's top submitter.

### Sample

For the sample database (the seed data is visible in the sample test), the output is:

\`\`\`
2016-03-01 4 11 Rose
2016-03-02 2 12 Angela
2016-03-03 1 13 Frank
2016-03-04 1 11 Rose
\`\`\`

On day 1 all four hackers submitted (count 4); all made 1 submission, so the lowest id (11, Rose) is the top submitter. On day 2 only hackers 11 and 12 kept their every-day streak (count 2); Angela made 2 submissions, the most. On day 3 only hacker 11 has submitted every day (count 1); Frank made 2 submissions. On day 4 the streak count is still 1; Rose made 2 submissions, the most that day.`;

// ---- stubs (schema-comment header + the generic SQL starter line) ---------------

const WS5_STUB = `-- STATION(ID INTEGER, CITY VARCHAR(50), STATE VARCHAR(2), LAT_N NUMERIC, LONG_W NUMERIC)
-- SQLite 3.27 - the table is already loaded; output formatting is preconfigured.
-- Write your SQL query below.
`;

const OCC_STUB = `-- OCCUPATIONS(Name VARCHAR(50), Occupation VARCHAR(20))
-- SQLite 3.27 - the table is already loaded; output formatting is preconfigured.
-- Write your SQL query below.
`;

const D15_STUB = `-- Hackers(hacker_id INTEGER, name VARCHAR(50))
-- Submissions(submission_date DATE, submission_id INTEGER, hacker_id INTEGER, score INTEGER)
-- SQLite 3.27 - the tables are already loaded; output formatting is preconfigured.
-- Write your SQL query below.
`;

// ---- the three conversions -------------------------------------------------------

const CONVERSIONS = {
  "weather-observation-station-5": { seed: ws5Seed, ref: WS5_REF, statement: WS5_STATEMENT, stub: WS5_STUB },
  "occupations": { seed: occSeed, ref: OCC_REF, statement: OCC_STATEMENT, stub: OCC_STUB },
  "15-days-of-learning-sql": { seed: d15Seed, ref: D15_REF, statement: D15_STATEMENT, stub: D15_STUB }
};

// ---- main -----------------------------------------------------------------------

const sqliteVersion = checkSqlite3();
console.log(`local sqlite3: ${sqliteVersion} (engine is 3.27.2 — reference queries are 3.27-safe)`);

const adapted = JSON.parse(readFileSync(EXTRACTION, "utf8"));
const payloads = [];
let failures = 0;

for (const problem of adapted) {
  const conversion = CONVERSIONS[problem.id];
  if (!conversion) {
    console.error(`FATAL: no conversion defined for ${problem.id}`);
    process.exit(1);
  }
  console.log(`\n=== ${problem.id} ===`);

  const convertTests = (tests, label) => tests.map((t, i) => {
    const seed = conversion.seed(t.input);
    if (seed.length > PROBLEM_BOUNDS.TEST_TEXT_MAX) {
      console.error(`  FAIL ${label}[${i}]: seed SQL ${seed.length} chars exceeds TEST_TEXT_MAX ` +
        `${PROBLEM_BOUNDS.TEST_TEXT_MAX} — trim dataset rows (keep the answer stable) and rerun.`);
      failures++;
    }
    // THE pipeline: identical composition to the exec handlers, local sqlite3.
    const expected = runSqlite(composeSqlExecSource(seed, conversion.ref));
    if (expected.length > PROBLEM_BOUNDS.TEST_TEXT_MAX) {
      console.error(`  FAIL ${label}[${i}]: expected output exceeds TEST_TEXT_MAX`);
      failures++;
    }
    // Answer-stability proof: the SQL pipeline must reproduce the adapted
    // problem's expected output (same dataset, same task, two solvers agree).
    const match = expected === t.expected;
    console.log(`  ${label}[${i}]: seed ${String(seed.length).padStart(4)} chars, ` +
      `expected ${String(expected.length).padStart(4)} chars, matches old expected: ${match ? "YES" : "NO"}`);
    if (!match) {
      console.error(`    old: ${JSON.stringify(t.expected)}`);
      console.error(`    new: ${JSON.stringify(expected)}`);
      failures++;
    }
    return { input: seed, expected };
  });

  const sampleTests = convertTests(problem.sample_tests, "sample");
  const hiddenTests = convertTests(problem.hidden_tests, "hidden");

  if (conversion.statement.length > 20000) {
    console.error(`  FAIL: statement ${conversion.statement.length} chars exceeds STATEMENT_MAX`);
    failures++;
  }

  payloads.push({
    id: problem.id,
    title: problem.title,
    statement: conversion.statement,
    statement_format: "markdown",
    languages: ["sql"],
    cpuTimeLimit: 5,
    memoryLimit: 128000,
    points: problem.points,
    scoring: problem.scoring,
    status: "published",
    sampleTests,
    hiddenTests,
    stubs: { sql: conversion.stub },
    tags: ["hr-clone", "kec-aerele", "sql"]
  });
}

if (failures) {
  console.error(`\n${failures} validation failure(s) — NOTHING written or posted.`);
  process.exit(1);
}

mkdirSync(HERE, { recursive: true });
writeFileSync(PAYLOADS_OUT, JSON.stringify(payloads, null, 2));
console.log(`\nAll validations passed. Payloads written to ${PAYLOADS_OUT}`);

const password = process.env.ADMIN_PASSWORD;
if (!password || DRY_RUN) {
  console.log(DRY_RUN
    ? "--dry-run: skipping API writes."
    : "ADMIN_PASSWORD not set: validate-only run (set it to convert the live problems).");
  process.exit(0);
}

// ---- apply: POST /api/admin/problems (same upsert route the clone run used) ----
for (const payload of payloads) {
  const response = await fetch(`${API}/api/admin/problems`, {
    method: "POST",
    headers: { "x-admin-password": password, "Content-Type": "application/json" },
    body: JSON.stringify(payload)
  });
  const body = await response.json().catch(() => ({}));
  console.log(`POST ${payload.id}: HTTP ${response.status} -> ${JSON.stringify(body.ok ?? body)}`);
  if (!response.ok || !body.ok) {
    console.error("Aborting on first failure.");
    process.exit(1);
  }
}
console.log("Conversion applied to the live problem bank.");
